### ISSUE TITLE
Confusing that pkg_install("foo") doesn't install from CRAN

### ISSUE THREAD

**Issue by hadley** [r-lib/pak#108]
If a package from github is already installed.

**Comment by gaborcsardi** [comment]
`pkg_install("cran::foo")` does

**Comment by hadley** [comment]
Yeah, it just keeps surprising me that it's a no-op.

**Comment by gaborcsardi** [comment]
We could do that, just need to be careful, because downstream it must have a different meaning.

**Comment by gaborcsardi** [comment]
Unfortunately we need some bigger internal changes to handle this sensibly. You basically want that if a package name appears in `pkg_install()` directly, then that should mean something different than appearing it in a dependency of another package. Which is entirely sensible, just needs some internal tooling update.

Right now all these packages are assumed to be `standard::` packages, basically meaning either CRAN or Bioconductor. Standard packages are satisfied by _any_ installed package. This is needed for the case when one packages wants a GH version of a dependency, and other packages also need this dependency. But this also means that if you run `pkg_install("foobar")`, then _any_ installed version of foobar is sufficient.

I will introduce a new remotes type, called `direct::`, which will mean either CRAN or Bioconductor (or from any configured CRAN-like repo).

**Comment by gaborcsardi** [comment]
Another potential issue with this is that if you have something like
```r
pkg_install(c("foo", "org/bar"))
```
and `org/bar` specifies `org/foo` as a dependency, then this would be a conflict, if we change `"foo"` to mean `"cran::foo"`.

And making `"foo"` mean different things depending on what other package are installed in the same call seems sub-optimal to me.

Maybe we can just get used to `"foo"` meaning `"any::foo"` i.e. foo from any source?

**Comment by hadley** [comment]
Let's let this sit a while now that you're writing the version numbers in the install messages. I think that will help a lot.

**Comment by gaborcsardi** [comment]
Some other ideas. 

1. If you run `pkg_install("foo")` interactively, and foo is already installed, pak would ask you if you meant `pkg_install("cran::foo")`? I don't love this too much, though. It is better to avoid these questions if possible, and just do the right thing.

2. In general, pak could print out the versions of the packages that are not updated. But I just removed the "not updating" message because both you and @jennybc found it annoying, so this is probably not the way forward.

3. Go ahead and make `pkg_install("foo")` mean `pkg_install("cran::foo")`, and if there is a conflict, then the user needs to solve it, e.g. by specifying `pkg_install("any::foo")`.

**Comment by gaborcsardi** [comment]
This was already fixed in pkgdepends.
