### ISSUE TITLE
Select specific versions for CRAN packages

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pak#122]
For R packages that need to be installed from the CRAN archive. E.g. https://github.com/r-lib/pak/blob/c85118b565dc9be753291d9b24c59f3f82b4c320/R/package.R#L26-L30

**Comment by hadley** [comment]
Looks like it needs to be copied over from https://github.com/r-lib/pkgdepends/blob/359d94554c70502d21861b9af70fbe95cc5f91ae/R/remotes.R#L47-L50

**Comment by gaborcsardi** [comment]
Well, you can't currently. This was supported before, and the parser sill parses it, but I temporarily removed it when re-organizing the internals. So it is not just documentation, I'll need to add it back.

**Comment by kenahoo** [comment]
@gaborcsardi are you saying specific versions (or version ranges) can't be used with pak anymore?  That seems like a pretty big deal since solving version dependencies is supposed to be one of the primary advantages of pak.  Or has this already been added back and this ticket just needs to be updated?

**Comment by willgearty** [comment]
Any chance this will be reintroduced in pak anytime soon @gaborcsardi?

**Comment by ColinFay** [comment]
👍 this, that would be an awesome feature
