### ISSUE TITLE
p_load function

### ISSUE THREAD

**Issue by higgi13425** [r-lib/pak#142]
Can you add the p_load function from pacman?
It is amazingly helpful in shared scripts. 

You don't have to worry about whether your recipient has the packages installed, as p_load will handle that.

And you no longer have separate install and library() steps. 
p_load reduces the cognitive load so that you can move on to data analysis with less friction.

**Comment by gaborcsardi** [comment]
Thanks for the suggestion! 

It is very unlikely that we would add such a function, because we believe that package installation and package loading are two very different operations and mixing them seems bad practice. For example upgrading a package while it is loaded in another R session may break that R session, whereas loading a package is safe.

I agree that an easy way to install all dependencies of a script is more than desirable. One way, that already works with pak, possibly also with remotes and similar tools, is to supply a `DESCRIPTION` file with the script. All entries in this `DESCRIPTION` file would be optional, but the `Depends` and the `Remotes` entries can be used to specify the script's dependencies, from CRAN, GitHub or other sources. Then you can use `pak::local_install_deps()` to install all of them, or the currently not exported `pak:::proj_install()` function to install them into a separate library that only belongs to the project.

I understand that even a small extra file be might too complicated for a single script file, so hopefully we can come up with an simpler solution.

One way would be to have a function in pak that parses a script file for `library()` and `loadNamespace()` calls, and then installs all these packages and their dependencies. It is not immediately clear how one would refer to non-CRAN packages here. Conditional and non-essential dependencies are also harder to express. Nevertheless, such a function seems useful.

Another way would be to list the dependencies of the script at the beginning of the script file, as comments, or a string literal. This does require some extra work, but it is more flexible, as one could easily refer to non-CRAN packages, using the `Remotes` syntax, and non-essential dependencies can also be expressed via `Suggests`.

I think both of these would be useful additions, and actually we could even have a single function that can do both. I.e. if there is dependency metadata at the beginning of the script, then it uses that, otherwise it parses the script for `library()` calls. Or, if a directory is given, parses all R files in the directory, recursively, for `library()` calls.

CC @jimhester

**Comment by higgi13425** [comment]
Dear Gabor,
Thanks for the thoughtful response.p_load is very much appreciated by beginners, who struggle with install and library,and often don't remember the difference.
Perhaps a polylibrary(package1, package2, package3)function without quotes would help reduce friction for new students to R.
Not sure if that function would make sense in this package or somewhere else.
Peter
    On Sunday, July 14, 2019, 1:57:25 PM EDT, Gábor Csárdi <notifications@github.com> wrote:  
 
 
Thanks for the suggestion!

It is very unlikely that we would add such a function, because we believe that package installation and package loading are two very different operations and mixing them seems bad practice. For example upgrading a package while it is loaded in another R session may break that R session, whereas loading a package is safe.

I agree that an easy way to install all dependencies of a script is more than desirable. One way, that already works with pak, possibly also with remotes and similar tools, is to supply a DESCRIPTION file with the script. All entries in this DESCRIPTION file would be optional, but the Depends and the Remotes entries can be used to specify the script's dependencies, from CRAN, GitHub or other sources. Then you can use pak::local_install_deps() to install all of them, or the currently not exported pak:::proj_install() function to install them into a separate library that only belongs to the project.

I understand that even a small extra file be might too complicated for a single script file, so hopefully we can come up with an simpler solution.

One way would be to have a function in pak that parses a script file for library() and loadNamespace() calls, and then installs all these packages and their dependencies. It is not immediately clear how one would refer to non-CRAN packages here. Conditional and non-essential dependencies are also harder to express. Nevertheless, such a function seems useful.

Another way would be to list the dependencies of the script at the beginning of the script file, as comments, or a string literal. This does require some extra work, but it is more flexible, as one could easily refer to non-CRAN packages, using the Remotes syntax, and non-essential dependencies can also be expressed via Suggests.

I think both of these would be useful additions, and actually we could even have a single function that can do both. I.e. if there is dependency metadata at the beginning of the script, then it uses that, otherwise it parses the script for library() calls. Or, if a directory is given, parses all R files in the directory, recursively, for library() calls.

CC @jimhester
