### ISSUE TITLE
Consider messaging around loaded packages

### ISSUE THREAD

**Issue by hadley** [r-lib/pak#174]
Should pkgload mention that they're currently loaded and that you'll need to restart R?

**Comment by gaborcsardi** [comment]
# Messages for loaded packages and locked DLLs

## NONE & NONE

No updated packages are loaded. No DLLs are locked by others. Nothing to print, no need for confirmation.

## LOADED & NONE

Some packages are loaded in the current session. No DLLs are locked. Need to print a warning:

```
! `waldo` and `cli` are loaded in the current R session, you will
probably need to restart R after the installation.
```

This is the only warning that is possibly printed on Unix. All others are related to the DLL locking and appear on Windows only

## LOCKED & NONE

Some packages locked DLLs in the current session. No DLLs are locked by others. We need to ask the confirmation to unload these packages:

```
! `rlang` and `testthat` are loaded in the current session and have
locked files in your library. The installation will probably fail,
unless pak unloads them, and also all other packages using them.

What do you want to do?

1 Have pak unload them before the installation. (Safest option.)
2 Try the installation without unloading them.
3 Abort the installation.

? Your choice [1]
```

In unloading is selected, then shows a status bar about the progress, and at the end shows a summary. If unloading has failed, then show a suggestion to restart R and run the installation in a clean R process, including not loading any package in your profile. Successful status bar:

```
→ Unloading `testthat`.
✓ Unloaded `testthat`.
✓ Unloaded 12 packages.
```

Unsuccessful unloading:

```
x pak failed to unload `testthat`. Re-try the installation after
restarting R. Make sure that no package are loaded from your R
profile.
```

## NONE & LOCKED

Nothing wrong in the current R session, but some DLLs are locked in other session(s). We need to ask if the user wants to close them, or we should terminate them.

```
! `rlang` and `testthat` are loaded in other R sessions and have
locked files in your library. The installation will probably fail,
unless you quit from these R sessions:

- rsession.exe (1234), in rstudio.exe (45223) (dplyr)
- Rterm.exe (4311), in rstudio.exe (45223) (dplyr)
- RGui.exe (19433)
- Rterm.exe (34443), in WindowsTerminal.exe (34441)

What do you want to do?

1 Quit these R sessions and try the installation again.
  (Safest option.)
2 Terminate the listed R sessions. They may lose data!
3 Try the installation anyway.
4 Abort the installation.

? Your choice [1]:
```

If termination is selected, then show a status bar, and a summary, like this:

```
→ Killing rsession.exe (1234).
✓ Killed rsession.exe (1234).
✓ Killed 4 R processes.
```

Unsuccessful termination:

```
x pak failed to terminate Rterm.exe (4311). Try to terminate it
manually, using the Task Manager.
```

## LOADED & LOCKED

Some packages are loaded in the current session, but no DLLs are locked. There are DLLs locked in other processes. Show the warning for the LOADED & LOCKED case first, and then use the same UI as for the NONE & LOCKED case.

## LOCKED & LOCKED

Both the current process and other processes have DLLs locked. If the set of packages locked in the current session and other sessions is the same, then we show a simplified message:

```
! `rlang` and `testthat` are loaded in the current R session and in
other R sessions and they have locked files in your library. The
installation will probably fail unless pak unloads them from
the current R session and you quit from these R sessions:

- rsession.exe (1234), in rstudio.exe (45223) (dplyr)
- Rterm.exe (4311), in rstudio.exe (45223) (dplyr)
- RGui.exe (19433)
- Rterm.exe (34443), in WindowsTerminal.exe (34441)

What do you want to do?

1 Quit the listed R sessions and then have pak unload the packages
  from the current R session (Safest option.)
2 Terminate the listed R sessions (the may lose data!) and have
  pak unload the packages from the current R session.
3 Try the installation anyway.
4 Abort the installation.

? Your choice [1]
```

We do the appropriate status bar messaging for the unloading and the termination. See above.
If the set of packages loaded in the current and other sessions is different, then we'll show a slightly longer message, but then the menu is the same. The message looks like this:

```
! `rlang` is loaded in the current R session and has locked files in
your library. The installation will fail unless pak unloads it.

! `glue` is loaded in other R sessions and has locked files in
your library. The installation will fail unless you quit from these
R sessions:

- rsession.exe (1234), in rstudio.exe (45223) (dplyr)
- Rterm.exe (4311), in rstudio.exe (45223) (dplyr)
- RGui.exe (19433)
- Rterm.exe (34443), in WindowsTerminal.exe (34441)
```

## Notes

* We could also warn to restart R after the installation has finished, if any packages were updated.
* We need to check for locked DLLs again, after the downloads have completed, because people might start another R session while the downloads are running.

**Comment by gaborcsardi** [comment]
## Workflow
The messaging has to be done in the sub-process, so then it is simpler to do the detection in the sub-process as well.

1. After making an installation plan, the sub-process checks for loaded packages and locked DLLs.
2. The sub-process does the appropriate messaging. 
3. The sub-process returns the status to the main process. The status contains the situation we are in (e.g. "locked-locked" and also which packages are loaded/locked in the current (main) process and also the ones locked by other processes. (The main process sends the sub-process the loaded packages in the first place.)
4. The main process prints either goes on with the installation if there are no issues, or asks the user about what to do. 
5. Depending on the answer, the main process either unloads some packages, or calls back to the sub-process to kill some processes. 
6. After this the main process calls the sub-process again, to check if everything was fixed, and we jump to step 2.
