### ISSUE TITLE
Offer package install condition handler

### ISSUE THREAD

**Issue by hadley** [r-lib/pak#272]
Listen to global package `packageNotFoundError` condition and offer to install package.

Could also restart in some situations, e.g. https://github.com/wch/r-source/blob/d23cb238e546b7a1e0339de1894ed2e356835b1e/src/library/base/R/namespace.R#L369

**Comment by gaborcsardi** [comment]
So, the caveat is that we cannot register the global handler from `.onLoad()`, and we cannot unregister it in `.onUnload()` because both are called with a non-empty handler stack, and that is not allowed.

A (rather nasty) trick is to use `addTaskCallback()` to register the global handler, and this almost works, but on some platforms the registered handler does not work, i.e. it is not called on error. This is probably an R bug. I don't really blame them for not testing `globalCallingHandlers()` from a task callback, though.

So currently what we can do is to provide a `global_handler()` function, which people can use in their `.Rprofile`. You can actually do this without loading pak, if you want to avoid that:

```r
if (interactive() && getRversion() >= "4.0.0") {
  globalCallingHandlers(
    packageNotFoundError = function(err) pak:::global_handler(err)
  )
}
```

And/or we could also provide some setup function that calls `globalCallingHandlers()` for you.

**Comment by jimhester** [comment]
I think just having a function one could add to their `.Rprofile` to set this up is probably best. CRAN is definitely not going to want pak adding something to the global handlers automatically onLoad or elsewhere.

**Comment by gaborcsardi** [comment]
I'll merge #274 to address this minimally, and I'll copy the questions from there here, and re-open this issue, so we can address them later, e.g. we can add a helper function that you can just call from the profile.

**Comment by gaborcsardi** [comment]
This is minimally done in #274, but we'll still improve it:

- [ ] Should we use `is_interactive()`, or just `interactive()`? Or neither, and this is up to the user?
- [ ] What if there is an active `sink()` and we cannot print to the screen?
- [ ] Should we have a `setup_global_handler()` function?
- [ ] Should we try to remove the handler when unloading?
- [ ] Should we ask the user about calling the restart instead of just calling it (if available)?
- [ ] Should we submit a patch to base R that moves the restart to `find.package()`, so that we'd have it for `library()` as well?
