### ISSUE TITLE
pak fails in github action (windows): error in `pkgs$platform[winbin] <- ifelse(is.na(archs) | archs %in% c("i386,x64", …`

### ISSUE THREAD

**Issue by MLopez-Ibanez** [r-lib/pak#448]
```
 shell: C:\R\bin\Rscript.EXE {0}
 env:
   pythonLocation: C:\hostedtoolcache\windows\Python\3.7.9\x64
   PKG_CONFIG_PATH: C:\hostedtoolcache\windows\Python\3.7.9\x64/lib/pkgconfig
   Python_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.7.9\x64
   Python2_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.7.9\x64
   Python3_ROOT_DIR: C:\hostedtoolcache\windows\Python\3.7.9\x64
   _R_INSTALL_TIME_PATCHES_: no
   R_LIBS_USER: D:\a\_temp\Library
   TZ: UTC
   _R_CHECK_SYSTEM_CLOCK_: FALSE
   NOT_CRAN: true
   RSPM: https://packagemanager.rstudio.com/all/latest
   RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/all/latest
   R_LIB_FOR_PAK: C:/R/site-library
 ##[endgroup]
 ##[group]Install/update packages
 ℹ Installing lockfile '.github/pkg.lock'
 Error: 
 ! error in pak subprocess
 Caused by error in `pkgs$platform[winbin] <- ifelse(is.na(archs) | archs %in% c("i386,x64", …`:
 ! replacement has length zero
 ---
 Backtrace:
 1. pak::lockfile_install(".github/pkg.lock")
 2. pak:::remote(function(...) { …
 3. err$throw(res$error)
 ---
 Subprocess backtrace:
 1. base::withCallingHandlers(cli_message = function(msg) { …
 2. get("lockfile_install_internal", asNamespace("pak"))(...)
 3. plan$update()
 4. pkgdepends:::pkg_lockfile_update(self, private)
 5. private$plan$update()
 6. pkgdepends:::pkgplan_update(self, private)
 7. pkgdepends:::make_installed_cache(private$config$get("library"))
 8. base::.handleSimpleError(function (e) …
 9. global h(simpleError(msg, call))
 Execution halted
```

**Comment by gaborcsardi** [comment]
Can you link to the missing build?

**Comment by MLopez-Ibanez** [comment]
Does this work: https://github.com/auto-optimization/iracepy/actions/runs/3687554301/jobs/6258053201#step:24:291 ?

**Comment by MLopez-Ibanez** [comment]
Deleting the cache fixed it. Let me see what happens if I use the cache again...

**Comment by gaborcsardi** [comment]
Can you try `pak-version: devel` to see if this has been fixed already?

**Comment by MLopez-Ibanez** [comment]
Still happening: https://github.com/auto-optimization/iracepy/actions/runs/3695926220/jobs/6259308631

**Comment by gaborcsardi** [comment]
It seems that this is an edge case in base R / CRAN. Your package does have a `/src` directory, but it does not have a library. The compiled code creates a couple of binaries in `/bin/<arch>` (in the installed package) instead.

Which is all fine, but because of the missing library, the base R packaging tools do not add an `Archs` entry to the metadata for your package, even though it is clearly not-architecture independent. I.e. https://cran.r-project.org/bin/windows/contrib/4.2/PACKAGES has:
```
Package: irace
Version: 3.5
Depends: R (>= 3.2.0)
Imports: stats, utils, compiler, R6
Suggests: Rmpi (>= 0.6.0), parallel, knitr, testthat, withr, mlr (>=
        2.15.0), ParamHelpers, devtools, covr
License: GPL (>= 2)
```
without an `Archs: x64` entry.

IDK if there is anything you could do to have this fixed on CRAN. 

For pak, we'll assume that the binary is x64 only for R 4.2.0 and above, and that it is i386 + x64 for older R versions. This should work well in practice.

**Comment by gaborcsardi** [comment]
A fix is now deployed in `pak-version: devel`, so hopefully it works now.
