### ISSUE TITLE
pak clobbers system source installs

### ISSUE THREAD

**Issue by mdsumner** [r-lib/pak#581]
when  run a docker image that includes from-source builds: 

```
docker run --rm -ti  ghcr.io/rocker-org/geospatial:dev-osgeo bash
```

and install pak, and use that to install a package with sys requirements: 

```R
install.packages("pak")
pak::pak("vapour")

```

```
→ Will install 2 packages.
→ Will download 2 packages with unknown size.
+ nanoarrow   0.3.0.1 [dl]
+ vapour      0.9.5   [dl] + ✖ libgdal-dev, ✖ gdal-bin, ✖ libproj-dev
→ Will install 3 system packages:
+ gdal-bin     - vapour
+ libgdal-dev  - vapour
+ libproj-dev  - vapour

```

that's all well, but I don't want it to install libgdal-dev, gdal-bin, or libproj-dev - gdal was compiled and installed here: 
https://github.com/rocker-org/rocker-versioned2/blob/f0ad63ba5b49768c3c333b8d4a54b3122b830aa6/scripts/experimental/install_dev_osgeo.sh#L203

is there something that install should be doing to ensure pak detects it as a valid system lib? Alternatively, can I as a pak user specify not to do that? 

I can use `devtools::install_cran("vapour")` and all is well, for example. Just not sure if the docker build process could do this differently. 

Thanks!

**Comment by gaborcsardi** [comment]
pak only detects proper system packages, that were installed with the system package manager. If you install packages other ways, e.g. the traditional `./configure; make install` way, those are not detected. This is usually not a big problem, even if pak installs extra packages, because the manually installed packages go into `/usr/local/`, which takes priority over system packages in `/usr`. 

Nevertheless, you can opt out from system dependency installation by setting the `PKG_SYSREQS=false` env var or the `pkg.sysreqs=FALSE` option: https://pak.r-lib.org/reference/pak-config.html#pak-configuration

**Comment by mdsumner** [comment]
ok thanks! 

it still installs though it looks promisingly like it's not going to do that, I'll keep exploring since this is not a very familar area for me - I guess the installs are bundled with everything somehow on the setup I'm using. 

```
options(pkg.sysreqs=FALSE)
> pak::pak("terra")
v Loading metadata database ... done

> Will update 1 package.
> Will download 1 package with unknown size.
+ terra 1.7-69 > 1.7-65 [dl] + x libgdal-dev, x gdal-bin, v libgeos-dev, v libproj-dev, v libsqlite3-dev
x Missing 2 system packages. You'll probably need to install them manually:
+ gdal-bin     - terra
+ libgdal-dev  - terra
? Do you want to continue (Y/n) Y
i Getting 1 pkg with unknown size
v Got terra 1.7-65 (x86_64-pc-linux-gnu-ubuntu-22.04) (4.21 MB)
v Downloaded 1 package (4.21 MB) in 3.4s
v Installed terra 1.7-65  (1s)
v 1 pkg + 1 dep: kept 1, upd 1, dld 1 (4.21 MB) [18.2s]
> terra::gdal()
[1] "3.4.1"
```

(would be 3.8.2 with rocker as above)
