### ISSUE TITLE
Colours in RStudio are suboptimal

### ISSUE THREAD

**Issue by hadley** [r-lib/pak#94]
<img width="537" alt="screen shot 2019-03-05 at 8 52 15 am" src="https://user-images.githubusercontent.com/4196/53813814-0c585980-3f24-11e9-9a7b-b0a0bebf4cac.png">

**Comment by gaborcsardi** [comment]
Three problems here.

1. The blue background is ugly, I adjusted that.
2. The repetition, that's the same RStudio bug that caused #95. I'll need to work  around that.
3. The text is red because it is coming from `message()`. I'll see what I can do about that, because the Rstudio bug might mean that I cannot change the colors...

**Comment by hadley** [comment]
Maybe the top-level process should display messages with `cat()`?

**Comment by gaborcsardi** [comment]
This is a temporary bug, it'll go away with the next RStudio release, so I think it is not worth to change that...

**Comment by jimhester** [comment]
FWIW a few weeks ago I did a simple proof of concept PR to rstudio to change the colors of messages. https://github.com/rstudio/rstudio/pull/4069, although it looks like more extensive changes would be necessary for full support.

**Comment by gaborcsardi** [comment]
Once that bug is fixed we can control the colors of the messages, simply with `message(blue("this is blue"))`.

But yeah, printing the messages in red is probably a bit too much.
